# file: group_vars/all/main.yml
# ALL VARIABLES FILLED WITH REAL VALUES BY
# Jan Pavlíček (xpavli95@stud.fit.vutbr.cz)
---
# Path of known hosts file
federation_registry_known_hosts_path: "~/.ssh/known_hosts"
# Ams Configuration
federation_registry_ams:
  # Consumer/Publisher for deployment tasks and deployment results topics
  authorized_users :
    - username: "rciam-federation-registry-devel"
  # Authentication key for the ams agent process
  agent_key : "<ANONYMIZED>"
  # Admin User token for setting the topics, subscriptions and ACL
  admin_token : "<ANONYMIZED>"
  # Consumer/Publisher User Token
  token: "<ANONYMIZED>"
  # Base Url of the Ams
  host: "https://api.devel.msg.argo.grnet.gr/v1"
  project: "rciam-service-registry"
  sub: "cesnet-push-subscription"
  topic: "cesnet-deployment-results-topic"
federation_registry_pm2_conf_path: "/home/debian"
federation_registry_react_folder: "federation-registry-frontend"
federation_registry_project_path: "/var/www/rciam-federation-registry"
federation_registry_react_path: "{{federation_registry_project_path}}/{{federation_registry_react_folder}}"
federation_registry_express_folder: "federation-registry-backend-api"
federation_registry_express_path: "{{federation_registry_project_path}}/{{federation_registry_express_folder}}"
federation_registry_ams_agent_folder: "federation-registry-backend-ams-agent"
federation_registry_ams_agent_path: "{{federation_registry_project_path}}/{{federation_registry_ams_agent_folder}}"
federation_registry_git:
  git_repo: "git@github.com:xpavlic/rciam-federation-registry.git"
  git_branch: "thesis"
  github_access_token: "<ANONYMIZED>"
  key_path: "/home/debian/.ssh/id_rsa.git"
  clone_dest: "~/rciam-federation-registry"
federation_registry_deployment_env : "dev"
federation_registry_key_title: "env-vm"
federation_registry_init_script: "setup_tenant.sql"
federation_registry_admin_key: "<ANONYMIZED>"
federation_registry_backend_token_key: "<ANONYMIZED>"
federation_registry_react_base_url: "/"
federation_registry_cors: "https://federation-registry.dev.perun-aai.org https://api.devel.msg.argo.grnet.gr"
# Hostname of vm that hosts the nginx
federation_registry_nginx_hostname: "federation-registry.dev.perun-aai.org"
rciam_dbs:
  federation:
    name: "service_registry_db"
    owner_username: "postgres"
    owner_password: "<ANONYMIZED>"
    host: "localhost"
    port: 5432
    script_path: /home/debian/setup_db.sql
federation_registry_tenant_config:
  - name: "cesnet"
    backend_uri: "https://federation-registry.dev.perun-aai.org/federation-backend/"
